name: mmr-aa-cyclone
channels:
  - conda-forge
dependencies:
  - python=3.11
  - python-dotenv
  - numpy
  - ocha-stratus
  - scipy
  - pandas
  - gdal
  - proj
  - shapely
  - cartopy
  - xarray
  - pip
  - pip: []