name: mmr-aa-cyclone
channels:
  - conda-forge
dependencies:
  - python=3.11
  - python-dotenv
  - climada
  - climada_petals
  - numpy
  - scipy
  - pandas
  - gdal
  - proj
  - pytz
  - shapely
  - cartopy
  - xarray
  - pip
  - pip:
      - ocha-stratus